spring:
  datasource:
    username: root
    password: prashantMac
    url: jdbc:mysql://localhost:3306/hotal
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update